[package]
name = "ssh-to-solana"
version = "0.1.0"
edition = "2024"
description = "Convert GPG-exported ED25519 SSH key to Solana address"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
base64 = "0.21"
bs58 = "0.5"
anyhow = "1.0"
