[package]
edition = "2024"
name = "crypto-rust-tools"
version = "0.1.0"

[dependencies]

[workspace]
members = [
    "frost-mpc-cli-node",
    "ssh-to-solana",
    "webrtc-signal-server",
    "webrtc-signal-server-cloudflare-worker",
    "yubikey-crpyto",
]
